# Generated by Django 4.1.2 on 2022-11-18 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='photos/')),
                ('title', models.CharField(max_length=255)),
                ('weight', models.IntegerField(blank=True)),
                ('cost', models.IntegerField(blank=True)),
            ],
        ),
    ]
