# Generated by Django 4.1.2 on 2022-11-23 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_food_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='weight',
            field=models.CharField(max_length=255),
        ),
    ]
