# Generated by Django 4.1.2 on 2022-11-23 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_food_weight'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='food',
            options={'ordering': ['pk'], 'verbose_name': 'Блюда', 'verbose_name_plural': 'Блюда'},
        ),
        migrations.AlterField(
            model_name='food',
            name='cost',
            field=models.IntegerField(blank=True, verbose_name='цена'),
        ),
        migrations.AlterField(
            model_name='food',
            name='photo',
            field=models.ImageField(upload_to='photos/', verbose_name='фото'),
        ),
        migrations.AlterField(
            model_name='food',
            name='title',
            field=models.CharField(max_length=255, verbose_name='заголовок'),
        ),
        migrations.AlterField(
            model_name='food',
            name='weight',
            field=models.CharField(max_length=255, verbose_name='вес'),
        ),
    ]
