# Generated by Django 4.1.2 on 2022-11-25 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_food_options_alter_food_cost_alter_food_photo_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('time_create', models.DateTimeField(auto_now_add=True)),
                ('txt', models.TextField()),
            ],
            options={
                'verbose_name': 'Комментарий',
                'verbose_name_plural': 'Коментарии',
                'ordering': ['time_create'],
            },
        ),
        migrations.AlterModelOptions(
            name='food',
            options={'ordering': ['pk'], 'verbose_name': 'Блюдо', 'verbose_name_plural': 'Блюда'},
        ),
    ]
