# Generated by Django 4.1.2 on 2022-12-02 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_post_alter_food_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('phoneNumber', models.CharField(error_messages='Обязательно!', max_length=12)),
                ('email', models.EmailField(max_length=100)),
                ('numberOfPeople', models.IntegerField()),
                ('data', models.DateField(error_messages='не корректная дата')),
                ('time', models.TimeField(error_messages='не корректное время')),
                ('reason', models.CharField(max_length=255)),
                ('accept', models.BooleanField(default=False)),
                ('isPass', models.BooleanField(default=False)),
            ],
        ),
    ]
