# Generated by Django 4.1.2 on 2022-12-02 13:55

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_book'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='accept',
            field=models.BooleanField(default=False, verbose_name='подтвержденно'),
        ),
        migrations.AlterField(
            model_name='book',
            name='data',
            field=models.DateField(error_messages='не корректная дата', verbose_name='дата'),
        ),
        migrations.AlterField(
            model_name='book',
            name='email',
            field=models.EmailField(max_length=100, verbose_name='почта'),
        ),
        migrations.AlterField(
            model_name='book',
            name='isPass',
            field=models.BooleanField(default=False, verbose_name='прошло'),
        ),
        migrations.AlterField(
            model_name='book',
            name='name',
            field=models.CharField(max_length=255, verbose_name='имя'),
        ),
        migrations.AlterField(
            model_name='book',
            name='numberOfPeople',
            field=models.IntegerField(verbose_name='количество человек'),
        ),
        migrations.AlterField(
            model_name='book',
            name='phoneNumber',
            field=models.CharField(max_length=17, validators=[django.core.validators.RegexValidator(message="'+999999999'", regex='^\\+?1?\\d{9,15}$')]),
        ),
        migrations.AlterField(
            model_name='book',
            name='reason',
            field=models.CharField(max_length=255, verbose_name='Повод посещения'),
        ),
        migrations.AlterField(
            model_name='book',
            name='time',
            field=models.TimeField(error_messages='не корректное время', verbose_name='время'),
        ),
    ]
